### PR TITLE
2.0 preview

### PR DESCRIPTION
**Pull request by tobilen**
- Updated structure according to https://www.polymer-project.org/2.0/docs/upgrade
- Append Container to document.body, then position it on top of a spacer element
- Add Resize Listener to keep Container positioned on top of spacer

### CODE REVIEW

**Comment by cbalit** [comment]
@tobilen nice work, thank you. Before merging your PR can you check the all demo repository pages and the unit test pages in the test repository. I just comit on master some fix for the bower components path.

**Comment by tobilen** [comment]
will do

**Comment by tteke** [comment]
Can you make this PR happen, cuz it actually solves the problem of the element not working in a local DOM.

**Comment by tobilen** [comment]
this project went on the backburner, which is why i havent updated demos and unit tests yet, sorry about that. i'll try to get to it this week.

in any case, you probably shouldnt merge this into master. polymer maintains separate 2.0-preview branches on all their components.

**Comment by tteke** [comment]
I meant that this solves the problem also in 1.0. I tried to put a captcha in a view in polymer starter kit and since the view itself is an element, the captcha goes into the endless loading loop, but using this branch solved it.

**Comment by cbalit** [comment]
There is an issue using document.body and absolute position. If the re-captcha is inside another element and you want to hide this element (using css display none for example) , the captcha will still be displayed on the page.

**Comment by cbalit** [comment]
@tteke i create a v1.1.3 version with the code of @tobilen in Polymer 1. To use it you have to add a **inbody** flag to the re-captcha

**Comment by cbalit** [comment]
@tobilen i just create a 2.0-preview branch. Can you create another PR from this branch. I will close this one

**Comment by tobilen** [comment]
cheers!

**Pull request closed without merging**
